### ISSUE TITLE
Cookie parsing error `called `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase`

### ISSUE THREAD

**Issue by mjsir911** [Ovyerus/bandsnatch#12]
Hi,

bandsnatch currently isn't parsing my `cookies.txt` file correctly:

```
.bandcamp.com	TRUE	/	TRUE	2028157437	client_id	XXXXXXXXXXXXXXXXXXXXXXXXX
```

```
 $ RUST_BACKTRACE=1 ./target/debug/bandsnatch run --format mp3-320 mjsir911 -c cookies.txt
thread 'main' panicked at src/cookies.rs:89:43:
called `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/result.rs:1073:23
   4: bandsnatch::cookies::fill_cookie_jar
             at ./src/cookies.rs:89:20
   5: bandsnatch::api::Api::new
             at ./src/api/mod.rs:37:26
   6: bandsnatch::cmds::run::command
             at ./src/cmds/run.rs:115:24
   7: bandsnatch::main
             at ./src/main.rs:40:36
   8: core::ops::function::FnOnce::call_once
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Ovyerus** [comment]
Hi, so sorry for taking a bit to get to this. It should be fixed in [v0.3.2](https://github.com/Ovyerus/bandsnatch/releases/tag/v0.3.2)!
